# Generated by Django 5.1.2 on 2025-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_publicholidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='created_on',
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_port',
            field=models.IntegerField(default=5432),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
