# Generated by Django 5.1.2 on 2025-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_remove_tenant_created_on_tenant_db_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='db_engine',
            field=models.CharField(default='django.db.backends.postgresql', help_text='Django DB engine path', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='health_con',
            field=models.CharField(default='good', help_text='Health status of tenant DB connection', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='time_zone',
            field=models.CharField(default='Africa/Johannesburg', help_text="IANA timezone (e.g. 'UTC', 'Africa/Johannesburg')", max_length=50),
        ),
    ]
