# Generated by Django 5.1.2 on 2025-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_company_alter_platformuser_tenant_devices_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_rep',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
