# Generated by Django 5.1.2 on 2025-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_alter_company_company_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
