# Generated by Django 5.1.2 on 2025-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_devices_password_devices_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
