# Generated by Django 5.1.2 on 2025-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_company_close_company_open_tenant_close_tenant_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sunday_is_normal_workday',
            field=models.BooleanField(default=False),
        ),
    ]
