# Generated by Django 5.1.2 on 2025-08-13 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('department', models.CharField(choices=[('FIN', 'Finance'), ('HR', 'Human Resources'), ('IT', 'Technical Support')], max_length=64, null=True)),
                ('position', models.CharField(max_length=64, null=True)),
                ('wage', models.FloatField(blank=True, null=True)),
                ('connected', models.CharField(blank=True, max_length=64, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=64)),
                ('site_address', models.CharField(max_length=64, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.employees')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.sites')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.sites'),
        ),
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=64, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField(blank=True, default=None, null=True)),
                ('normal_hours', models.FloatField(blank=True, default=None, null=True)),
                ('overtime_normal_saturdays', models.FloatField(blank=True, default=None, null=True)),
                ('overtime_holiday_sundays', models.FloatField(blank=True, default=None, null=True)),
                ('signed_off', models.CharField(blank=True, max_length=64, null=True)),
                ('signed_off_by', models.CharField(blank=True, max_length=64, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.sites')),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_alias', models.CharField(max_length=100)),
                ('db_host', models.CharField(blank=True, max_length=255, null=True)),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('db_user', models.CharField(blank=True, max_length=255, null=True)),
                ('db_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
