# Generated by Django 5.1.2 on 2025-08-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_publicholidays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicHolidays',
        ),
    ]
