# Generated by Django 5.1.2 on 2025-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_delete_publicholidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemanagers',
            name='user',
        ),
        migrations.AddField(
            model_name='sitemanagers',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagers',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
