# Generated by Django 5.1.2 on 2025-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_remove_sitemanagers_user_sitemanagers_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemanagers',
            name='manager_site_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
