# Generated by Django 5.1.2 on 2025-08-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_sitemanagers_manager_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemanagers',
            name='manager_site_id',
        ),
    ]
