# Generated by Django 5.1.2 on 2025-09-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_company_alter_platformuser_tenant_devices_company_and_more'),
        ('timesheets', '0006_remove_sitemanagers_manager_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.company'),
        ),
        migrations.AddField(
            model_name='sitemanagers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.company'),
        ),
        migrations.AddField(
            model_name='sites',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.company'),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.company'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
