# Generated by Django 5.1.2 on 2025-09-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_employees_company_sitemanagers_company_sites_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('JUR', 'Junior'), ('Mid', 'Middle Management'), ('SEN', 'Senior Management')], max_length=64, null=True),
        ),
    ]
