# Generated by Django 5.1.2 on 2025-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_employees_id_number_alter_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
